// Generated by CoffeeScript 1.6.3
(function() {
  var OR_USE_MODEL, OR_USE_STARS, SELECT_MODEL, addNewAppliance;

  SELECT_MODEL = "Search for model";

  OR_USE_STARS = "or use stars";

  OR_USE_MODEL = "or search model";

  window.modelInput = function() {
    return $('<input>').addClass('model').attr({
      type: 'text',
      value: SELECT_MODEL
    }).focusin(function() {
      if (this.value === SELECT_MODEL) {
        return this.value = "";
      }
    }).focusout(function() {
      if (!this.value) {
        return this.value = SELECT_MODEL;
      }
    });
  };

  window.getStarInput = function() {
    var j, stars, starspan, _i, _j;
    starspan = $('<span>').addClass('stars');
    stars = [];
    for (j = _i = 0; _i < 6; j = ++_i) {
      _j = j;
      stars.push($('<span>').click(function() {
        var k, _k, _l, _ref, _results;
        for (k = _k = 0; 0 <= _j ? _k <= _j : _k >= _j; k = 0 <= _j ? ++_k : --_k) {
          stars[k].addClass('active');
        }
        _results = [];
        for (k = _l = _ref = _j + 1; _ref <= 6 ? _l < 6 : _l > 6; k = _ref <= 6 ? ++_l : --_l) {
          _results.push(stars[k].removeClass('active'));
        }
        return _results;
      }));
    }
    return starspan.append(stars);
  };

  window.getNewRow = function() {
    var newRow;
    newRow = $('<tr>').append($('<td>').html('<select id="applianceType">\
				<option value="">Select appliance</option>\
				<option value="airconditioner">Air conditioner</option>\
				<option value="clothesdryer">Clothes dryer</option>\
				<option value="computormonitors">Computor monitor</option>\
				<option value="dishwashers">Dishwasher</option>\
				<option value="fridgefreezer">Fridge/Freezer</option>\
				<option value="television">Television</option>\
			</select>')).append($('<td>').addClass('input').html(modelInput())).append($('<td>').append($('<a>').html(OR_USE_STARS).attr('href', "javascript:void(0);").addClass('use-stars-button').click(function() {
      var jthis;
      jthis = $(this);
      if (jthis.html() === OR_USE_MODEL) {
        jthis.html(OR_USE_STARS);
        return newRow.find('.input').html(modelInput());
      } else {
        jthis.html(OR_USE_MODEL);
        return newRow.find('.input').html(getStarInput());
      }
    }))).append($('<td>'));
    return newRow;
  };

  addNewAppliance = function() {
    return $('.appliance-table').append(getNewRow());
  };

  $(document).ready(function() {
    addNewAppliance();
    return $('#addAppliance').click(addNewAppliance);
  });

  window.resultsReady = (function() {
    var res;
    res = false;
    return function(val) {
      res = val;
      if (res) {
        $('.navbox li').addClass('navigable');
      } else {
        $('.navbox li').removeClass('navigable');
      }
      return res;
    };
  })();

}).call(this);
