// Generated by CoffeeScript 1.6.3
(function() {
  var ROW_STRING, SELECT_MODEL;

  SELECT_MODEL = "Select model";

  ROW_STRING = '<td>\
		<select id="applianceType">\
			<option value="airconditioner">Air conditioner</option>\
			<option value="clothesdryer">Clothes dryer</option>\
			<option value="computormonitors">Computor monitor</option>\
			<option value="dishwashers">Dishwasher</option>\
			<option value="fridgefreezer">Fridge/Freezer</option>\
			<option value="television">Television</option>\
		</select>\
	</td>\
	<td><input class="model" type="text" value="' + SELECT_MODEL + '"></input></td>\
	<td><a class="use-stars-button" href="javascript:void(0);">or use energy stars</a></td>\
	<td></td>';

  window.addNewAppliance = function() {
    var newRow;
    newRow = $('<tr>').html(ROW_STRING);
    newRow.find("input").focusin(function() {
      if (this.value === SELECT_MODEL) {
        return this.value = "";
      }
    }).focusout(function() {
      if (!this.value) {
        return this.value = SELECT_MODEL;
      }
    });
    return $('.appliance-table').append(newRow);
  };

  $(document).ready(function() {
    addNewAppliance();
    return $('#addAppliance').click(addNewAppliance);
  });

}).call(this);
